### ISSUE TITLE
In paprica_build.sh, "paprica_place_it.py", line 166... KeyError 'ref' 

### ISSUE THREAD

**Issue by karoraw1** [bowmanjeffs/paprica#29]
I used the material in the v0.22 branch. I used `paprica_build.sh` and got past the RAxML issue I had previously I think, because there is a RAxML_distances file. From the nature of the error message, I might have gotten through `paprica_make_ref.py` to the end (woo!). This might be a problem that you mentioned in an earlier issue, but there didn't appear to be an open issue that applied.

```bash

[Parallel(n_jobs=-1)]: Done 4107 out of 4107 | elapsed: 422.1min finished
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    8.5s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:  4.7min
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  9.7min
[Parallel(n_jobs=-1)]: Done 272 tasks      | elapsed: 20.3min
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed: 51.6min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed: 86.4min
[Parallel(n_jobs=-1)]: Done 866 tasks      | elapsed: 145.1min
[Parallel(n_jobs=-1)]: Done 1136 tasks      | elapsed: 169.7min
[Parallel(n_jobs=-1)]: Done 1442 tasks      | elapsed: 192.8min
[Parallel(n_jobs=-1)]: Done 1784 tasks      | elapsed: 236.9min
[Parallel(n_jobs=-1)]: Done 2162 tasks      | elapsed: 272.6min
[Parallel(n_jobs=-1)]: Done 2576 tasks      | elapsed: 347.5min
[Parallel(n_jobs=-1)]: Done 3026 tasks      | elapsed: 403.4min
[Parallel(n_jobs=-1)]: Done 3512 tasks      | elapsed: 464.4min
[Parallel(n_jobs=-1)]: Done 4034 tasks      | elapsed: 531.8min
[Parallel(n_jobs=-1)]: Done 4107 out of 4107 | elapsed: 541.4min finished
rm: cannot remove ‘/home/login/Desktop/paprica-0.22/ref_genome_database/*dist’: No such file or directory
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    8.2s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  3.5min
[Parallel(n_jobs=-1)]: Done 272 tasks      | elapsed:  6.5min
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed: 10.6min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed: 15.4min
[Parallel(n_jobs=-1)]: Done 866 tasks      | elapsed: 20.9min
[Parallel(n_jobs=-1)]: Done 1136 tasks      | elapsed: 27.4min
[Parallel(n_jobs=-1)]: Done 1442 tasks      | elapsed: 34.8min
[Parallel(n_jobs=-1)]: Done 1784 tasks      | elapsed: 43.0min
[Parallel(n_jobs=-1)]: Done 2162 tasks      | elapsed: 52.3min
[Parallel(n_jobs=-1)]: Done 2576 tasks      | elapsed: 62.6min
[Parallel(n_jobs=-1)]: Done 2697 out of 2697 | elapsed: 65.5min finished
Traceback (most recent call last):
  File "paprica_place_it.py", line 166, in <module>
    ref = command_args['ref']        
KeyError: 'ref'
```

I will look at this harder throughout today and see if I can figure out something.

**Comment by bowmanjeffs** [comment]
That's an easy fix.  I've been making a lot of improvements to the commands and added the flags -ref and -query to make it easier to implement paprica_place_it.py (and also -n and -splits flags, see latest manual).  I suspect that I never added those flags to the paprica_place_it.py line in paprica_run.sh for v0.22.  Make sure that the line in your paprica_run.sh file has a -ref flag:
```paprica_place_it.py -ref combined_16S.tax```
And don't forget to comment out the paprica_make_ref.py command now that you're officially past that hurdle!  I'll keep this issue open pending confirmation that that fixed the problem.

**Comment by karoraw1** [comment]
Adding the -ref flag fixed this issue. At some point soon after commencing, it spat out: `rm: cannot remove ‘/home/login/Desktop/paprica-0.22/ref_genome_database/*ref.tre’: No such file or directory`, but it is still running now, so if there is another issue, downstream it is probably unrelated to this one. I'll let you know if something comes up.

**Comment by bowmanjeffs** [comment]
Sounds good.  You'll note those rm errors pop up from time to time... when it is necessary to clean up the workspace or for steps that can't overwrite an existing file I just throw in the rm command.  If there's nothing to clean up you get the error.  So long as paprica keeps running nothing is actually amiss.
