### ISSUE TITLE
raxml version needs to be changed in paprica-make_ref.py too

### ISSUE THREAD

**Issue by blancaverag** [bowmanjeffs/paprica#38]

**Comment by bowmanjeffs** [comment]
In both cases it looks like you didn't run the command correctly.  It should be:

./paprica-run.sh test.bacteria bacteria 

...to run the file test.bacteria.fasta against the bacteria database.  Let me know if that works, and also let me know if the instructions were incorrect somewhere so I can get that fixed...

Jeff

---- BVG wrote ----

**Comment by blancaverag** [comment]
Thank you, I realized and was running the rest of the installation test and changing the issue with the new errors.

As suggested in the manual, and as I could not install the appropiate RAxML version, I changed the RAxML version in paprica-place_it.py, but I found that was not enough; paprica-make_ref.py also calls it.

I am now running into this other error:

...
raxmlHPC -T 2 -m GTRGAMMA -f J -p 12345 -t /home/programas/paprica/ref_genome_database/bacteria/RAxML_rootedTree.root.ref.tre -n conf.root.ref.tre -s /home/programas/paprica/ref_genome_database/bacteria/combined_16S.bacteria.tax.clean.align.fasta -w /home/programas/paprica/ref_genome_database/bacteria/ 


Time after model optimization: 0.151178
Initial Likelihood -6021.645307

NNI interchanges 0 Likelihood -6021.645165

Final Likelihood of NNI-optimized tree: -6021.645165

RAxML NNI-optimized tree written to file: /home/programas/paprica/ref_genome_database/bacteria/RAxML_fastTree.conf.root.ref.tre

Same tree with SH-like supports written to file: /home/programas/paprica/ref_genome_database/bacteria/RAxML_fastTreeSH_Support.conf.root.ref.tre

Total execution time: 0.234270
Traceback (most recent call last):
  File "/usr/local/bin/taxit", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2805, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 696, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 594, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: xlrd
cp: no se puede crear el fichero regular «/home/programas/paprica/ref_genome_database/bacteria/combined_16S.bacteria.tax.refpkg/combined_16S.bacteria.tax.clean.align.sto»: No existe el fichero o el directorio
cmalign :: align sequences to a CM
INFERNAL 1.1.2 (July 2016)
...

xlrd is installed at /usr/local/bin/anaconda.

**Comment by bowmanjeffs** [comment]
It looks like you're running into a problem with taxit.  The error suggests to me that taxit is running with your system Python and not Anaconda.  That shouldn't be a problem so long as taxit installed correctly, however, it appears that it did not.  Try re-installing taxit, possibly using the Anaconda distro to install.
