### ISSUE TITLE
Virtual box

### ISSUE THREAD

**Issue by AnweshaGhosh** [bowmanjeffs/paprica#49]
Hi,

I have been trying to install Paprica using Virtual Machine but this error keeps showing up

Could not create the imported medium 'C:\Users\Dell1\VirtualBox VMs\paprica-demo\paprica-demo-disk001.vmdk'.
VMDK: Compressed image is corrupted 'C:\Users\Dell1\paprica-demo-disk001.vmdk' (VERR_ZIP_CORRUPTED).

Result Code: 
VBOX_E_FILE_ERROR (0x80BB0004)
Component: 
ApplianceWrap
Interface: 
IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}

I have redownloaded the file about 5 times now and the same error shows. It says the file is corrupted. How can I check? 

Thank you,
Anwesha

**Comment by bowmanjeffs** [comment]
Hmmm, I just downloaded and imported without a problem.  Hash the appliance with md5 and make sure that the checksum is: ffea7083ad49a7b276b8bf8ba1608c91:

CertUtil -hashfile paprica-demo.ova MD5

If the checksums don't match it's probably a download issue and you should try a different method of downloading (e.g. different browser or use wget).
