### ISSUE TITLE
paprica did not work

### ISSUE THREAD

**Issue by camel315** [bowmanjeffs/paprica#56]
@bowmanjeffs I am new with your paprica package. When I fowllow your examples, 
it shows ./paprica-run.sh rep_set bacteria
./paprica-run.sh: line 26: paprica-place_it.py: command not found
after I add 'python' before  'paprica-place_it.py -ref_dir ref_genome_database', it went forward, but another error info like:

...
Error: HMM banded truncated alignment mxes need 1587.20 Mb > 1028.00 Mb limit.
Use --mxsize, --maxtau or --tau.
/bin/bash: esl-alimerge: command not found
/bin/bash: seqmagick: command not found
/bin/bash: pplacer: command not found
/bin/bash: guppy: command not found
/bin/bash: guppy: command not found
/bin/bash: rppr: command not found
/bin/bash: guppy: command not found
...
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File /home/syang/paprica/rep_set.combined_16S.bacteria.tax.clean.align.csv does not exist

...

Could you please help me to figure it out?
Thank you.

**Comment by bowmanjeffs** [comment]
It looks like a few things are going on here.  The "Error: HMM banded truncated alignment mxes need 1587.20 Mb > 1028.00 Mb limit." error suggests that your reads are either low quality, still have primers attached, have chimeras, or something along those lines.  Double check your QC steps to make sure they are sufficient.

The other errors suggest that the dependencies are not installed, or have not been added to PATH.  Double check that this is the case (be sure to read the tutorials if you aren't sure how to do this), and let me know if you're still have trouble.
