### ISSUE TITLE
add a setup.py and upload to pypi

### ISSUE THREAD

**Issue by nick-youngblut** [bowmanjeffs/paprica#59]
It seems that `paprica` is mostly set up like a python package, but it seems to be missing `setup.py` (and the other needed files). Since it is not a standard software package, installing `paprica` with a software management tool (eg., `pip` or `conda`) is difficult. So, this limits how easily the user can install, manage, and reproduce the software environment used for any analyses involving `paprika`. 

It would be really helpful if you converted `paprika` into a full-fledged python package that's hosted on pypi (or better yet, `bioconda`). `paprika` seems to have a lot of software dependencies, but the installation of these can be handled by `conda` (the joys of a software manager). An added benefit of this approach is that it is easier to include continuous integration for testing your package :)

**Comment by nick-youngblut** [comment]
Thanks for the quick reply! Yeah, it can be hard to convert software into a standard package format after it is already built. It is best to start the project with a package skeleton in place (eg., by using [cookiecutter](https://github.com/audreyr/cookiecutter)), but "how to develop a software package" is often left out of bioinformatics classes, which mainly just teach you how to write simple scripts and algorithms. It's really too bad, and it hurts the reproducibility of bioinformatics data analyses.

**Comment by bowmanjeffs** [comment]
If I ever get the opportunity to redesign the whole pipeline I'll definitely consider it.  Thanks for the link to cookiecutter, I wan't familiar with that tool!
