### ISSUE TITLE
Wrong argument in make_edge_fasta.py?

### ISSUE THREAD

**Issue by Gustius** [bowmanjeffs/paprica#66]
When trying the make_edge_fasta.py, I got an empty file as output. Upon inspecting make_edge_fasta.py, I think I found the error: name = line[1] refers to the origin, not the name, which is line[0]. After changing this, it worked again.

https://github.com/bowmanjeffs/paprica/blob/ae21d9e774152011775ba2c37ecbf3aaff2e1681/utilities/make_edge_fasta.py#L56

**Comment by bowmanjeffs** [comment]
There is a new make_edge_fasta that more simply uses the unique csv and fasta file, I just hadn't committed it to the repository yet.  Should be available now!
