### ISSUE TITLE
SettingWithCopyWarning: harmless or a bigger problem?

### ISSUE THREAD

**Issue by Gustius** [bowmanjeffs/paprica#67]
At the end of running paprica-run.sh, I get some warnings. Are these just harmless or do I have a problem? Here the last lines of the output where these warnings appear:

Normalizing abundance for unique sequences...
/home/gust/.local/lib/python2.7/site-packages/pandas/core/indexing.py:362: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/home/gust/.local/lib/python2.7/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/home/gust/.local/lib/python2.7/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)
Thanks for using paprica!  Please be sure to read through the manual, and check out the tutorials at www.polarmicrobes.org

**Comment by bowmanjeffs** [comment]
These are just warnings, there are no issues.  They seem to be generated internally by different functions within Python, as I've fixed all warnings that cite a location in the paprica scripts.
