### ISSUE TITLE
Single edn reads preprocessing

### ISSUE THREAD

**Issue by roman-spanek** [bowmanjeffs/paprica#70]
Dear Jeff, 
I was wondering if you might be interested in a script that prepares input files for paprica from single end reads (IonTorrent). I would be happy to share.

**Comment by bowmanjeffs** [comment]
Certainly!  The best thing to do is fork the repository, then add your 
script to the "utilities" directory and make any necessary changes to 
the documentation, then push the changes to me.  Alternatively you can 
send it to me directly, but pushing is better.

Cheers,
Jeff

=============================

Jeff S. Bowman

Assistant Professor

Integrative Oceanography Division

Scripps Institution of Oceanography

www.polarmicrobes.org


------ Original Message ------

**Comment by roman-spanek** [comment]
Great, I’ll comment the script a little bit and push it into the repo.

 

Cheers,

Roman
