### ISSUE TITLE
problem with infernal when running ./paprica-run.sh test bacteria

### ISSUE THREAD

**Issue by lottedemaeyer** [bowmanjeffs/paprica#72]
Dear Jeff,

When I try to run: **./paprica-run.sh test bacteria** I get the following error:
./paprica-run.sh: line 26: paprica-pick_domain.py: command not found
./paprica-run.sh: line 30: paprica-place_it.py: command not found

When I check these lines in the scripts it says: **infernal**

However, when I installed infernal (easel instelled seperately) I don't get any error messages.
Do you have any idea what could be wrong?

Thanks in advance!

Cheers,
Lotte

**Comment by iaj2y** [comment]
Hi Lotte,

you have to include paprica in your PATH. For example, run the following in your terminal:

export PATH=$PATH:/<your paprica directory>

**Comment by bowmanjeffs** [comment]
You can follow the install instructions here for osx: https://www.polarmicrobes.org/installing-paprica-on-mac-osx/.  In particular note the section on adding appropriate files to PATH.  If you're installing on Linux installation is a bit simpler, but you still need to add files to PATH.
