### ISSUE TITLE
Proper citation forwarding

### ISSUE THREAD

**Issue by lczech** [bowmanjeffs/paprica#85]
Dear paprica developers,

it is really cool to see that phylogenetic placement is used in many areas of research now, and I am particularly grateful that you haven chosen to use our tools epa-ng and gappa for this purpose! Hope that you find our work useful and easy to integrate - if you have any issues or suggestions, feel free to reach out to me! Oh also, awesome name for your tool - paprica!

There is but one thing that we would ask of you: Given that citations are the currency in academia, we would greatly appreciate to receive some as well from users that use epa-ng and gappa via paprica. I guess that the same is true for the developers of infernal and seqmagick.

So, could you please add the following references (and potentially infernal and seqmagick as well) as "additional publications to be cited when using paprica" (or the like) to all relevant places (readme, wiki, or wherever else you list the paprica reference):

> EPA-ng: Massively Parallel Evolutionary Placement of Genetic Sequences.
> Pierre Barbera, Alexey M Kozlov, Lucas Czech, Benoit Morel, Diego Darriba, Tomáš Flouri, Alexandros Stamatakis.
> Systematic Biology, syy054, https://doi.org/10.1093/sysbio/syy054

> Genesis and Gappa: processing, analyzing and visualizing phylogenetic (placement) data.
> Lucas Czech, Pierre Barbera, and Alexandros Stamatakis.
> Bioinformatics, 2020. https://doi.org/10.1093/bioinformatics/btaa070

For example, PICRUSt2, which also uses epa-ng and gappa, does this nicely, see [here](https://github.com/picrust/picrust2/wiki).

Thank you in advance, cheers
Lucas

**Comment by lczech** [comment]
Addendum: I just saw that the switch to epa-ng and gappa was relatively recent, thanks for the effort involved in this! If I may ask, why did you change? Speed, I reckon? 

Also, I'm always looking for inspiration for useful commands to integrate into gappa, so if there are any cool tasks that you think the tool should be able to do, please let me know ;-)

**Comment by bowmanjeffs** [comment]
Lucas,
This has been on my mind and I’m more than a little embarrassed that you had to nudge me to take action on something this important!  I agree completely that the default should be to cite the relevant tools within the pipeline.  I’ll update our README with the citations and ask users to use them.  For papers coming from my lab this will be standard practice moving forward.

Cheers,
Jeff

(I'll answer the addendum separately)

**Comment by lczech** [comment]
Hey Jeff,

thank you very much for the quick reply! That sounds good to me, and I am happy to hear that you agree on this and had it in mind already ;-)

All the best
Lucas

**Comment by bowmanjeffs** [comment]
For sure!  In response to your addendum... this has been on my to-do list for a long time.  pplacer and guppy were such wonderful tools but it didn't make sense to keep using them once they were no longer under development.  I will definitely let you know about features for gappa!

**Comment by bowmanjeffs** [comment]
Citations added to our README.  I've also added a prompt to the paprica-run.sh script to remind users to cite dependencies.

**Comment by lczech** [comment]
Awesome, thank you so much, Jeff!
