### ISSUE TITLE
Potential problem with test.bacteria.phylum_reps 

### ISSUE THREAD

**Issue by PaulTillich** [bowmanjeffs/paprica#86]
Hello, 

First I wanted to thank you for making this program, I first started using paprica about a year ago and thoroughly enjoyed how easy it was to use and how detailed/useful the output is!

I have recently tried to use paprica to rerun some sequences in preparation for a manuscript, but have run into some issues. We first ran into an issue on our Mac OS involving OpenMP and gappa, which we were able to overcome after some assistance from the maker of gappa. https://github.com/lczech/gappa/issues/15

Though we have now run into an additional problem that doesn't seem to be directly related to gappa. The creator of gappa gives a suggestion about where the problem may be, but isn't too sure since they are not familiar with paprica.  https://github.com/lczech/gappa/issues/15

So, if you had any thoughts or suggestions for how this issue would be addressed we would be super grateful for your advice! Thank you again for your time and help with this, we appreciate it very much!!!

    Gabriels-MacBook-Air:paprica gabrielprice$ ./paprica-run.sh test bacteria
    # cmalign :: align sequences to a CM 
    # INFERNAL 1.1.1 (July 2014)
    # Copyright (C) 2014 Howard Hughes Medical Institute.
    # Freely distributed under the GNU General Public License (GPLv3).
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # CM file:                                     /Users/gabrielprice/paprica/models/bacteria_ssu.cm
    # sequence file:                               /Users/gabrielprice/paprica/test.bacteria.clean.unique.fasta
    # CM name:                                     SSU_rRNA_bacteria
    # saving alignment to file:                    /Users/gabrielprice/paprica/test.bacteria.clean.unique.align.sto
    # output alignment format specified as:        Pfam
    # output alignment alphabet:                   DNA
    # number of worker threads:                    4
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    #                                                                              running time (s)                 
    #                                                                       -------------------------------          
    # idx  seq name      length  cm from    cm to  trunc    bit sc  avg pp  band calc  alignment      total  mem (Mb) 
    # ---  ------------  ------  -------  -------  -----  --------  ------  ---------  ---------  ---------  --------
        1  SRR953432.50      84      968     1054     3'     39.93   0.974       0.03       0.04       0.07      2.91
        2  Firmicutes_1     252      524      776  5'&3'    231.71   0.997       0.08       0.02       0.10      5.77
        3  Firmicutes_2     253      524      776  5'&3'    238.32   1.000       0.08       0.02       0.10      5.83
    #
    # CPU time: 0.41u 0.05s 00:00:00.46 Elapsed: 00:00:00.32
    # Saving alignment to file         /Users/gabrielprice/paprica/test.bacteria/test.bacteria.combined_16S.bacteria.tax.phylum_reps.clean.unique.align.sto     ...     done
    #
    # CPU time: 0.00u 0.01s 00:00:00.01 Elapsed: 00:00:00.02
    INFO Selected: Output dir: /Users/gabrielprice/paprica/test.bacteria/
    INFO Selected: Query file: /Users/gabrielprice/paprica/test.bacteria/test.bacteria.clean.unique.align.newlength.fasta
    INFO Selected: Tree file:         /Users/gabrielprice/paprica/ref_genome_database/bacteria/phylum_reps/combined_16S.23S.bacteria.tax.phylum_reps.f.       inal.bestTree
    INFO Selected: Reference MSA:         /Users/gabrielprice/paprica/test.bacteria/combined_16S.bacteria.tax.phylum_reps.clean.align.newlength.fasta
    INFO Selected: Automatic switching of use of per rate scalers
    INFO Selected: Preserving the root of the input tree
    INFO Selected: Specified model file:         /Users/gabrielprice/paprica/ref_genome_database/bacteria/phylum_reps/combined_16S.23S.bacteria.tax.phylum_reps.f.       inal.bestModel
    INFO    Rate heterogeneity: GAMMA (4 cats, mean),  alpha: 0.469537 (user),  weights&rates: (0.25,0.0278902)         (0.25,0.231564) (0.25,0.796771) (0.25,2.94377) 
            Base frequencies (user): 0.220039 0.236043 0.303232 0.240686 
            Substitution rates (user): 0.893602 2.60232 1.46235 0.917758 3.56951 1
    INFO     ______ ____   ___           _   __ ______
            / ____// __ \ /   |         / | / // ____/
           / __/  / /_/ // /| | ______ /  |/ // / __  
          / /___ / ____// ___ |/_____// /|  // /_/ /  
         /_____//_/    /_/  |_|      /_/ |_/ \____/ (v0.3.6)
    INFO Output file: /Users/gabrielprice/paprica/test.bacteria/epa_result.jplace
    INFO 3 Sequences done!
    INFO Time spent placing: 0s
    INFO Elapsed Time: 0s
                                                  ....      ....  
                                                 '' '||.   .||'   
                                                      ||  ||      
                                                      '|.|'       
         ...'   ....   ... ...  ... ...   ....        .|'|.       
         |  ||  '' .||   ||'  ||  ||'  || '' .||      .|'  ||      
         |''   .|' ||   ||    |  ||    | .|' ||     .|'|.  ||     
        '....  '|..'|'. ||...'   ||...'  '|..'|.    '||'    ||:.  
        '....'          ||       ||                               
                       ''''     ''''   v0.6.1 (c) 2017-2020
                                       by Lucas Czech and Pierre Barbera

    Invocation:                        gappa examine edpl --allow-file-overwriting --out-dir     /Users/gabrielprice/paprica/test.bacteria/     --file-prefix test.bacteria.phylum_reps.edpl --jplace-path
                                       /Users/gabrielprice/paprica/test.bacteria/test.bacteria.phylum_reps.jplace
    Command:                           gappa examine edpl
    
    Input:
      --jplace-path                    /Users/gabrielprice/paprica/test.bacteria/test.bacteria.phylum_reps.jplace
    
    Settings:
      --histogram-bins                 25
      --histogram-max                  -1
      --no-list-file                   false
    
     Output:
       --out-dir                        /Users/gabrielprice/paprica/test.bacteria/
       --file-prefix                    test.bacteria.phylum_reps.edpl
      --file-suffix
    
     Global Options:
       --allow-file-overwriting         true
       --verbose                        false
       --threads                        2
      --log-file
      
    Run the following command to get the references that need to be cited:
    `gappa tools citation Czech2020-genesis-and-gappa Matsen2011-edgepca-and-squash-clustering`.   
    
    Started 2021-01-28 21:31:54

    Found 1 jplace file
    Writing output files.
    
    Finished 2021-01-28 21:31:54
    The following arguments were not expected: test.bacteria.phylum_reps --tree-file-prefix
    Run with --help for more information.
    Traceback (most recent call last):
      File "/Users/gabrielprice/paprica/paprica-place_it.py", line 1340, in <module>
        edpl = pd.read_csv(temp_dir + query + '.' + phylum_ref + '.edpllist.csv', index_col = 1)
      File "/Library/Python/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
        return _read(filepath_or_buffer, kwds)
      File "/Library/Python/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
        parser = TextFileReader(fp_or_buf, **kwds)
      File "/Library/Python/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
        self._make_engine(self.engine)
      File "/Library/Python/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
        self._engine = CParserWrapper(self.f, **self.options)
      File "/Library/Python/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1906, in __init__
        self._reader = parsers.TextReader(src, **kwds)
      File "pandas/_libs/parsers.pyx", line 380, in pandas._libs.parsers.TextReader.__cinit__
      File "pandas/_libs/parsers.pyx", line 687, in pandas._libs.parsers.TextReader._setup_parser_source
     FileNotFoundError: [Errno 2] File b'/Users/gabrielprice/paprica/test.bacteria/test.bacteria.phylum_reps.edpllist.csv'     does     not exist: b'/Users/gabrielprice/paprica/test.bacteria/test.bacteria.phylum_reps.edpllist.csv'

**Comment by bowmanjeffs** [comment]
Hmmm…. Strange.  Can you confirm you’re using a clone of the current repository, including your local paprica-run.sh script?

 

Jeff

 

=======================

Jeff Bowman

Assistant Professor

Scripps Institution of Oceanography

www.polarmicrobes.org

**Comment by PaulTillich** [comment]
Hi Jeff,

I don't know what to tell you, but paprica started working suddenly and gave me the output I was looking for. My computer crashed and rebooted (unrelated to paprica). When it rebooted I ran paprica again so I could accurately respond to your question, but it just started working fine. 

Thank you for your help!

**Comment by bowmanjeffs** [comment]
Ha ha, glad it's working!
