### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'test.bacteria.phylum_reps.edpllist.csv'

### ISSUE THREAD

**Issue by lee-s17** [bowmanjeffs/paprica#87]
Hi,
I am installing paprica via git clone https://github.com/bowmanjeffs/paprica.git
When running ./paprica-run.sh test bacteria, the error pops up.
[testrun.txt](https://github.com/bowmanjeffs/paprica/files/5956899/testrun.txt)
 
Previously when I downloaded paprica v6 using "wget https://github.com/bowmanjeffs/paprica/archive/paprica_v0.6.tar.gz", it runs fine without error, so wondering what might lead to this error.

*Just realised this is the same error in#86. I tried reinstalling but the issue persists.

**Comment by lee-s17** [comment]
Thanks for the reply. Unfortunately, I tried to reclone but the same error persists. Attaching an image with the output files from running ./paprica-run.sh test bacteria. 
![Screenshot 2021-02-11 001855](https://user-images.githubusercontent.com/50101962/107539626-1c910d00-6c00-11eb-944a-bb5c4f4fd21c.jpg)

**Comment by bowmanjeffs** [comment]
It looks like your version of gappa doesn't understand the --tree-file-prefix option.  Can you update gappa and try again?

**Comment by bowmanjeffs** [comment]
Looking closer at this I looks like gappa is naming your EDPL file differently than expected (paprica expects *edplelist.csv and you're getting *edpledple_list.csv).  It looks like you're running the same gappa version as our test box, but let me know how you installed an what platform you're running on.  Perhaps there are differences...

**Comment by bowmanjeffs** [comment]
It looks like this is caused by a recent update to gappa.  Should have a fix implemented shortly.  Standy by...

**Comment by bowmanjeffs** [comment]
Okay should be good.  Reopen this issue if problems persist.
