### ISSUE TITLE
unambigously specify user for the linux install script

### ISSUE THREAD

**Issue by RJ333** [bowmanjeffs/paprica#94]
Hello together,
just wanted to mention that the current line https://github.com/bowmanjeffs/paprica/blob/master/linux_install.sh#L8
could be understand in a way that executing the script as root is fine...but as most linux distribution don't have /home/root but rather /root, the $PATH variable gets later wrongly configured

**Comment by bowmanjeffs** [comment]
Thanks for pointing that out, updated the install script.
